# Generated by Django 4.2.7 on 2023-12-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_sparkles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sparkles',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
