# Generated by Django 4.2.7 on 2023-12-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_sparkles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sparkles',
            field=models.IntegerField(null=True),
        ),
    ]
