# Generated by Django 4.2.7 on 2023-12-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_sparkles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wearing',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
