# Generated by Django 4.2.7 on 2023-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_wearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owns',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
