# Generated by Django 4.2.7 on 2023-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_owns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buttons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='colors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='font',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='volume',
            field=models.BooleanField(default=True),
        ),
    ]
