# Generated by Django 4.2.7 on 2023-12-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_buttons_profile_colors_profile_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
