# Generated by Django 4.2.7 on 2023-12-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='color',
        ),
    ]
