# Generated by Django 4.2.7 on 2023-12-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owns',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wearing',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
