# Generated by Django 4.2.7 on 2023-12-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_color_alter_profile_owns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(default='default', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owns',
            field=models.CharField(default='null', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wearing',
            field=models.CharField(default='null', editable=False, max_length=100, null=True),
        ),
    ]
