# Generated by Django 4.2.7 on 2023-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_first_login_alter_profile_buttons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owns',
            field=models.CharField(default='null', max_length=400, null=True),
        ),
    ]
